### ISSUE TITLE
Re-login with every Method call?

### ISSUE THREAD

**Issue by Wade-BuildOtto** [reactioncommerce/meteor-ddp-login#5]
from what I am gathering, in order to make any method calls to the server that uses the UserId I have to login with every call? 

is there no way to keep the user logged in so the server can reference the user to make method calls  with meteor user. 

so confusing that it wouldn't work this way.

**Comment by jshimko** [comment]
Nope.  `DDP.connect()` creates an instance that you can reuse as many times as you'd like.

```js
// create the connection instance
const conn = DDP.connect(remoteUrl);

// this sets 'conn' to a logged in state
DDP.loginWithPassword(conn, { username }, password);

// call as many methods as you want
const result1 = conn.call('method1', args1);
const result2 = conn.call('method2', args2);
const result3 = conn.call('method3', args3);

// when you're done...
conn.disconnect();
```

**Comment by Wade-BuildOtto** [comment]
when I do that the UserId on the 2nd server comes up as Null I tried
Meteor.userid, this.userid, Meteor.user

its working the publications outside the call but I couldn't figure out the
methods.

**Comment by aldeed** [comment]
Someone mentioned to me awhile back that this package may not be handling reconnect properly, might be losing auth state when the connection is disrupted. I never had time to look into it. Might be related.

**Comment by aldeed** [comment]
@Wade-BuildOtto It would also be helpful to know what version of Meteor / DDP is running on each server

**Comment by Wade-BuildOtto** [comment]
Might be something their, I am running the ddp login on 1.3.4 and on the
server 1.4.2

The 1.3.4 is going on a raspberry pi as a hub and the 1.4.2 is on modulus
running an ios and android app

Has ddp-client been updated in this process, don't see how it would work
for published collections and not methods, I'll look further and see if Its
something I setup funny on the server I did move the hub methods to another
server file so might be something with that.

Thank you for the help, really appreciate it.

**Comment by kwoodbury1** [comment]
For trouble shooting, you may want to watch the DDP state transitions.
If there are any problems in your application, you can call DDP.connect again until you find root cause.
I have included some sample code.  FYI - I have some Ubuntu servers running where they are connected all the time, and sharing information every five (5) seconds.  I checked this AM, and one pair of Ubuntu servers have been connected for 38 days straight.  I am using meteor version 1.3.4 on both servers.

	// create the connection instance
	const Remote = DDP.connect(remoteUrl);

	// this sets 'conn' to a logged in state
	DDP.loginWithPassword(Remote, { username }, password);

	// check connection status
	Tracker.autorun(function () {
              if (Remote.status().status === "connected") {
                  Meteor.settings.DDPtransitions += " then connected";
                  console.log(">>connected; DDP transitions: " + Meteor.settings.DDPtransitions);
              }
              else if (Remote.status().status === "connecting") {
                 console.log(">>connecting");
                 Meteor.settings.DDPtransitions += " then connecting";
              }
              else if (Remote.status().status === "waiting") {
                  console.log(">>waiting");
                  Meteor.settings.DDPtransitions = "waiting";
              }
              else {
                  console.log(">>disconnected");
              }

          });

Hope this helps.  
Kerry

**Comment by Wade-BuildOtto** [comment]
I ended up wrapping it into a Meteor.wrapAsync function, it was calling the
methods before it was actually logged in.

Thanks again for the help.

Your connection status script helped out to, being able to watch the change
in connection state.
